### ISSUE TITLE
panic at runtime on android

### ISSUE THREAD

**Issue by Milerius** [kpango/fastime#41]
```
E/Go: panic: unaligned 64-bit atomic operation
E/Go: 
E/Go: goroutine 8 [running]:
E/Go: runtime/internal/atomic.panicUnaligned()
E/Go: 	/Users/milerius/sdk/go1.16.2/src/runtime/internal/atomic/unaligned.go:8 +0x38
E/Go: runtime/internal/atomic.Store64(0x8684e2f4, 0x4c4b40, 0x0)
E/Go: 	/Users/milerius/sdk/go1.16.2/src/runtime/internal/atomic/asm_386.s:213 +0x10
E/Go: github.com/kpango/fastime.(*Fastime).StartTimerD.func1(0x8684e2c0, 0x4c4b40, 0x0, 0xb7422b9c, 0x86812820)
E/Go: 	/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-681244108/pkg/mod/github.com/kpango/fastime@v1.0.16/fastime.go:188 +0x88
E/Go: created by github.com/kpango/fastime.(*Fastime).StartTimerD
E/Go: 	/var/folders/9w/h3xyrgx538g23bw10m59tbgc0000gn/T/gomobile-work-681244108/pkg/mod/github.com/kpango/fastime@v1.0.16/fastime.go:185 +0xc9
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8080 (Thread-2), pid 8045 (e.myapplication)
```

https://github.com/golang/go/issues/11891

Would be nice if we can solve it, i try to make fasthttp work on my android device, and i'm block at this point

cc @kpango i dont know if you ever see this problem

> Reference: [golang/go#599](https://github.com/golang/go/issues/599) and https://golang.org/pkg/sync/atomic/#pkg-note-BUG
> Solution: [golang/go#11891 (comment)](https://github.com/golang/go/issues/11891#issuecomment-433623786)

**Comment by Milerius** [comment]
it's works @kpango with the last version i'm able to start my program and log on both ios and android device thanks alot
